/*
* EBS - RTFS (Real Time File Manager)
*
* Copyright EBS Inc 1987-2003
* All rights reserved.
* This code may not be redistributed in source or linkable object form
* without the consent of its author.
*/
/* drromdsk.c - Rom disk device driver.

Summary

 Description
    Provides a rom drive capability.

    This utility requires romdisk.h which is generated by the mkrom utility

*/
#include "rtfs.h"
#include "portconf.h"   /* For included devices */
#if (INCLUDE_ROMDISK)


/* Include the rom disk data */

#include "drromdsk.h"
/* extern byte  romdisk_data[];
*/

byte  *romdisk_block(int driveno, word block)                                       /*__fn__*/
{
word byte_number;
    RTFS_ARGSUSED_INT(driveno);
    /* Get the page number */
    byte_number = (word) (block * 512);
    return((byte  *)&romdisk_data[byte_number]);
}


/* BOOLEAN romdisk_io(dword block, void *buffer, word count, BOOLEAN reading)
*
*   Perform io from the romdisk. 
*
*   If the reading flag is true copy data from the romdisk (read).
*   
*
*/

BOOLEAN romdisk_io(int driveno, dword block, void  *buffer, word count, BOOLEAN reading) /*__fn__*/
{
    byte  *p;
    int i;
    byte  *pbuffer;

    pbuffer = (byte  *)buffer;

    while (count)
    {
        if (!reading)
            return(FALSE);
        p = romdisk_block(driveno, (word) block);
        if (!p)
            return(FALSE);
        for (i = 0; i < 512; i++)
            *pbuffer++ = *p++;
        count--;
        block++;   
    }
    return(TRUE);
}





int romdisk_perform_device_ioctl(int driveno, int opcode, void * pargs)
{
DDRIVE *pdr;
    RTFS_ARGSUSED_PVOID(pargs);
    pdr = pc_drno_to_drive_struct(driveno);
    if (!pdr)
        return (-1);

    switch (opcode)
    {
        /* Getgeometry and format share common code */
        case DEVCTL_GET_GEOMETRY:
        case DEVCTL_FORMAT:
            return(-1);
        case DEVCTL_CHECKSTATUS:
            return(DEVTEST_NOCHANGE);
        case DEVCTL_WARMSTART:
            pdr->drive_flags |= DRIVE_FLAGS_VALID;
            return(0);
            /* Fall through */
        case DEVCTL_POWER_RESTORE:
            /* Fall through */
        case DEVCTL_POWER_LOSS:
            /* Fall through */
        default:
            break;
    }
    return(0);

}
#endif /* (INCLUDE_ROMDISK) */

